
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package front.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int True = 44;
  public static final int Until = 24;
  public static final int loop = 25;
  public static final int add = 7;
  public static final int Repeat = 23;
  public static final int colons = 2;
  public static final int mod = 11;
  public static final int If = 16;
  public static final int gte = 14;
  public static final int gt = 42;
  public static final int op_or = 6;
  public static final int Else = 21;
  public static final int comma = 35;
  public static final int string = 33;
  public static final int end = 28;
  public static final int val_id = 38;
  public static final int func = 30;
  public static final int Return = 36;
  public static final int read = 18;
  public static final int While = 22;
  public static final int val_str = 39;
  public static final int op_and = 5;
  public static final int then = 19;
  public static final int sub = 8;
  public static final int prog = 27;
  public static final int EOF = 0;
  public static final int val_int = 37;
  public static final int error = 1;
  public static final int lt = 15;
  public static final int equals = 43;
  public static final int False = 45;
  public static final int lte = 40;
  public static final int lparen = 12;
  public static final int endif = 20;
  public static final int integer = 32;
  public static final int rparen = 13;
  public static final int mult = 9;
  public static final int endloop = 26;
  public static final int Const = 31;
  public static final int logic = 34;
  public static final int assign = 3;
  public static final int print = 17;
  public static final int noteq = 41;
  public static final int div = 10;
  public static final int method = 29;
  public static final int scolon = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "colons",
  "assign",
  "scolon",
  "op_and",
  "op_or",
  "add",
  "sub",
  "mult",
  "div",
  "mod",
  "lparen",
  "rparen",
  "gte",
  "lt",
  "If",
  "print",
  "read",
  "then",
  "endif",
  "Else",
  "While",
  "Repeat",
  "Until",
  "loop",
  "endloop",
  "prog",
  "end",
  "method",
  "func",
  "Const",
  "integer",
  "string",
  "logic",
  "comma",
  "Return",
  "val_int",
  "val_id",
  "val_str",
  "lte",
  "noteq",
  "gt",
  "equals",
  "True",
  "False"
  };
}

