package back.data_structures;

public enum Operation {
    PMB,GOTO,CALL,PARAM_C,PARAM_S,RTN,SKIP,ASIGNA,SUMA,RESTA,MULTIPLICACION,DIVISION,MODULO,IFMAYORIGUAL,IFIGUAL,IFMAYOR,IFMENORIGUAL,IFMENOR,IFDIFERENTE,AND,OR,IF,DESPLAZAR_BITS
}
